services:
  dass-desktop:
    image: ghcr.io/meta-smart-factory-d-o-o/dass-desktop:latest
    container_name: dass-desktop
    network_mode: host
    restart: always
    env_file: .env
    environment:
      - DISPLAY=${DISPLAY:-:0}
    volumes:
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix
      - dass-logs:/app/logs
    privileged: true

volumes:
  dass-logs:
