#!/bin/bash
set -e

echo "==> Generating system.ini from environment variables..."

mkdir -p /opt/meta/conf

cat > /opt/meta/conf/system.ini << EOF
#Generated by entrypoint.sh at $(date)

# --- Panel-Specific (from env) ---
settings.workstationId=${WORKSTATION_ID}
settings.panelId=${PANEL_ID}

# --- Client-Specific (from env) ---
customerName=${CUSTOMER_NAME}

# MySQL
mysql.datasource.driverClass=com.mysql.cj.jdbc.Driver
mysql.datasource.jdbcUrl=jdbc\:mysql\://${MYSQL_HOST}\:${MYSQL_PORT}/${MYSQL_DB}?allowPublicKeyRetrieval=true&useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&autoReconnect=true&useSSL=false
mysql.datasource.username=${MYSQL_USER}
mysql.datasource.password=${MYSQL_PASSWORD}

# RabbitMQ
rabbit.host=${RABBIT_HOST}
rabbit.port=${RABBIT_PORT:-5672}
rabbit.username=${RABBIT_USER:-dass}
rabbit.password=${RABBIT_PASSWORD}

# Kafka
kafka.host=${KAFKA_HOST:-localhost}
kafka.port=${KAFKA_PORT:-9092}
kafka.topic=${KAFKA_TOPIC:-panel-events}
kafka.username=${KAFKA_USER}
kafka.password=${KAFKA_PASSWORD}

# Host
host=http\://${MSF_HOST}\:7189/

# --- Fixed Defaults (hardcoded per developer confirmation) ---
mysql.datasource.initialPoolSize=1
mysql.datasource.minPoolSize=1
mysql.datasource.maxPoolSize=10
mysql.datasource.acquireIncrement=2
mysql.datasource.acquireRetryAttempts=1000000000
mysql.datasource.acquireRetryDelay=2000
mysql.datasource.maxConnectionAge=20
mysql.datasource.maxIdleTime=5
mysql.datasource.timeout=20000
mysql.datasource.unreturnedConnectionTimeout=20
mysql.datasource.debugUnreturnedConnectionStackTraces=true
mysql.datasource.numHelperThreads=3
rabbit.queue.multimachine=queue.multimachine
settings.workcenterId=425
settings.workstationName=GENERIC
settings.wareHouseId=406
settings.shiftId=12
settings.theme=2
settings.theme.darcula=false
settings.activeJobOrderIndex=1
settings.manuelStateCalculation=false
settings.minCycleInterval=8571
settings.multiScreen=0
settings.newIOActive=false
settings.powerConsumptionCoefficient=1
settings.singleJobMachine=true
settings.singleProduct=false
language=TR
country=US
meta.os=linux
panel.device=GENERIC
io.IODataId=0
newio.IODataId=187
pat.patDataId=63
plc.load.job=true
plc.stop.reason=true
scheduled.login.check.delay=120000
scheduled.login.check.period=600000
show.print.dialog=true
show.print.interactive=true
stream.max_packet_lenght=82
stream.mode=true
EOF

echo "==> Checking for latest meta.jar..."

if [ -z "$JAR_VERSION" ] || [ "$JAR_VERSION" = "latest" ]; then
    LATEST_TAG=$(wget -qO- https://api.github.com/repos/${JAR_REPO:-nuriozalp/download}/releases/latest | jq -r '.tag_name')
    echo "==> Latest version: $LATEST_TAG"
    JAR_URL="https://github.com/${JAR_REPO:-nuriozalp/download}/releases/download/${LATEST_TAG}/meta.jar"
else
    JAR_URL="https://github.com/${JAR_REPO:-nuriozalp/download}/releases/download/${JAR_VERSION}/meta.jar"
fi

if [ ! -f /opt/meta/meta.jar ] || [ "$AUTO_UPDATE" = "true" ]; then
    echo "==> Downloading meta.jar..."
    wget -O /opt/meta/meta.jar "$JAR_URL"
fi

echo "==> Starting Meta Panel..."
exec java \
    --add-opens=java.base/java.lang=ALL-UNNAMED \
    -Djavax.accessibility.assistive_technologies \
    -Djavax.accessibility.screen_magnifier_present=false \
    -jar /opt/meta/meta.jar
